name: android_club_app
description: "Official Android Club App"


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.1.0
  firebase_auth: 5.1.0
  firebase_storage: ^12.0.1
  google_sign_in: ^5.0.4
  flutter_svg: ^1.1.0+1
  cloud_firestore: ^5.1.0
  get_it: ^7.2.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  image_picker: ^0.8.4+4
  url_launcher: ^6.3.0
  firebase_database: 11.1.2
  video_player: ^2.2.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  assets:
    - assets/images/
    - assets/images/splash.mp4
    - assets/images/icon.png
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"



